version: '3.8'
services:
  perforce:
    build: .
    container_name: perforce
    ports:
      - "1666:1666"
    volumes:
      - ./data:/perforce-data
    environment:
      P4PORT: 1666
      P4USER: admin
      P4PASSWD: Passw0rd123!
      P4ROOT: /perforce-data
      P4DEPOTS: /perforce-data/depots
      DEBIAN_FRONTEND: noninteractive
